M48
; DRILL file {KiCad 9.0.0} date 2025-03-05T10:58:34+0100
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-05T10:58:34+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.200
%
G90
G05
T1
X113.025Y-48.275
X113.025Y-105.275
X133.525Y-48.275
X133.525Y-105.275
M30
