name: Sync GitHub Wiki to GitBook

on:
  schedule:
    - cron: '0 12 * * *'
  push:
    branches:
      - wiki  # Gatilho para alterações na Wiki
  workflow_dispatch:

jobs:
  sync_wiki:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Wiki repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}.wiki
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Push Wiki changes to GitBook repository
        run: |
          git remote add gitbook https://oauth2:${{ secrets.GITBOOK_TOKEN }}@github.com/GouTupan.git
          git push -f gitbook wiki:main  # Sincroniza a Wiki com a branch principal do GitBook
          
